### PR TITLE
Fix "pattern var x in method equals is never used" warning in generated code

### PR DESCRIPTION
**Pull request by razvan-panda**
#107

### CODE REVIEW

**Comment by razvan-panda** [comment]
@eed3si9n Nice talking to you too. And many thanks to OlegYch_ and earldouglas also.

**Comment by razvan-panda** [comment]
@eed3si9n Ah, I need to update the tests also I think.

**Comment by razvan-panda** [comment]
Woohoo haha

**Comment by dwijnand** [comment]
Nice one.

**Comment by dwijnand** [comment]
Can we cut a release with this please?

**Pull request merged**
