### PR TITLE
implement reference equality for scala

### PR DESCRIPTION
**Pull request by jtjeferreira**
improve runtime performance of equals method by testing for reference equality first.

### CODE REVIEW

**Comment by jtjeferreira** [comment]
need to fix this for scala 2.12...

**Comment by jtjeferreira** [comment]
Ready for review

**Review by eed3si9n — APPROVED** [review]
overall LGTM
Could you update the docs - https://github.com/sbt/contraband/blob/master/docs/02-code-generation.md, and also the description of this PR stating the motivation for this change (runtime perf I assume?)

**Comment by jtjeferreira** [comment]
@eed3si9n can you do a release so we get this change in sbt?

**Comment by eed3si9n** [comment]
https://github.com/sbt/contraband/releases/tag/v0.5.1 is out now.

**Pull request merged**
